"""empty message

Revision ID: 8732b0af2bd5
Revises: b47ce934073a
Create Date: 2018-12-16 19:20:19.102870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8732b0af2bd5'
down_revision = 'b47ce934073a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'modified_at')
    # ### end Alembic commands ###
